exclude = [
    'https://www.figma.com/.*',
    'https://gitlab.pg.innopolis.university/.*',
    'https://t.me/.*',
    'https://docs.google.com/.*',
    'https://drive\.google\.com/.*',
    'http://10\.93\.26\.179/.*',
    'http://localhost.*',
    'http://127\.0\.0\.1.*'
]